[env:esp32-s3-devkitc-1]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    knolleary/PubSubClient
    bblanchon/ArduinoJson @ ^7.0.0
    mathertel/OneButton @ ^2.0.3
    madhephaestus/ESP32Servo @ ^1.1.1
    arduino-libraries/NTPClient @ ^3.2.1

build_flags = 
    -Wno-deprecated-declarations
    -DCORE_DEBUG_LEVEL=0